---
title: "GAMUT DM Survey 2015"
author: "Rollie Parrish"
date: "April 17, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readr)
library(dplyr)
library(REDCapR)

```

## Purpose

- update all records with the data manager's email address
- export survey participants with email and program name

## ToDo

[ ] Load data from Mailman, DM signup forms, and GAMUT programs
[ ] 


```{r load data }

gamut <- 
    read_csv("../../data/DM_survey/GAMUTDatabase_DATA_LABELS_2016-04-17_1225.csv") %>%
    select(dag=`Data Access Group`, 
           program_name = `Program Name`, 
           dm_email = `Data manager email`, 
           dm_firstname = `Data Manager first name`,
           dm_lastname = `Data Manager last name`) %>%
    mutate(dm_email = tolower(dm_email))

signup <- 
    read_csv("../../data/DM_survey/DatabaseManagers_DATA_LABELS_2016-04-17_1224.csv") %>%
    select(dag=`Data Access Group`, 
           dm_email = `Repeat Data Manager's email`, 
           dm_firstname = `Data Manager's First Name`,
           dm_lastname = `Data Manager's Last Name`) %>%
    mutate(dm_email = tolower(dm_email))

listserv <- 
    read_csv("../../data/DM_survey/gamut_dm_listserv.txt", col_names = "dm_email") %>%
    mutate(dm_email = tolower(dm_email))

gamut_dms <- 
    gamut %>%
    left_join(signup, by = "dag") %>%
    mutate(dm_email = ifelse(dm_email.x == "", dm_email.y, dm_email.x), 
           dm_firstname = ifelse(dm_firstname.x =="", dm_firstname.y, dm_firstname.x), 
           dm_lastname = ifelse(dm_lastname.x == "", dm_lastname.y, dm_lastname.x)) %>%
    select(dag, program_name, dm_email, dm_firstname, dm_lastname, everything())


```


```{r update missing emails, eval = FALSE}

## update GAMUT with missing DM emails
gamut_missing_dm_email <- 
    gamut_dms %>%
    mutate(redcap_event_name = "initial_arm_1") %>%
    filter(dm_email.x == "") %>%
    filter(program_name != "AirMed International") %>%
    select(program_name, redcap_event_name, dm_email)

uri <- "https://ampa.org/redcap/api/"
token <- "FDBC7FF9D30D0CC1BCA6652C05A8AA23"

redcap_write_oneshot(gamut_missing_dm_email, redcap_uri = uri, token = token)


```

```{r export survey invitations, eval = FALSE}
survey_invitations <- 
    gamut_dms %>%
    mutate(survey_ident = paste(dag, " - ", dm_firstname, dm_lastname)) %>%
    select(dm_email, survey_ident) %>%
    filter(!is.na(dm_email)) %>%
    distinct(dm_email) %>%
    data.frame()


# load survey invitations into clipboard
writeClipboard(survey_invitations)

```

```{r check all on listserv }

missing_listserv <- 
    gamut_dms %>%
    select(dm_email) %>%
    anti_join(listserv)


```

