---
title: "GAMUT results"
author: "`r params$program_name`"
date: "September 2, 2016"
output: html_document
params:
  start_date: 2015-07-01
  end_date: 2016-06-01
  program_name: AEL AL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r initial_setup, echo=FALSE, message=FALSE, warning=FALSE}
library(REDCapR)
library(knitr)
library(plyr)
library(dplyr)
library(magrittr)
library(GAMUT)
library(zoo)
library(beeswarm)
library(qicharts)


options(scipen = 10)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = "")


source('beeswarm_plot.R')
source('beeswarm_plot_1k.R')
source('beeswarm_plot_10k.R')
source('shadowtext.R')
source('show_plotData.R')
source('metric_results.R')
source('show_runchart.R')


```
```{r load_data, eval = TRUE}
# Uncomment next line to get new data from REDCap
#GAMUT_data("GAMUT.Rdata")
load("GAMUT.Rdata")

## time data
time_data <- 
        monthly_data %>%
        select(program_name, month, total_patients, mean_mobilization, stemi_cases,
               mean_bedside_stemi, mean_scene_stemi) %>%
    filter(month < params$end_date)

runchart_data <- 
    monthly_data

# Filter past 12 months 
monthly_data <- filter(monthly_data,
                       month >= params$start_date & 
                       month < params$end_date)

#dag <- program_name
#operator <- params$operator
program_name <- params$program_name

```



```{r neo_vent_adv_airway, fig.height = 4, fig.path="figures/", include=TRUE, eval=TRUE, message=FALSE, echo=FALSE, warning=FALSE, error=FALSE}

metric_results(measure = "AA-1d", program = program_name)


```
