---
title: "Multiple programs plot"
author: "Rollie Parrish"
date: "September 17, 2016"
output:
  pdf_document: default
  html_document: default
params:
  dag: 
  end_date: '2016-06-01'
  org: AIM
  program_name: Akron Childrens
  start_date: '2015-07-01'
---


```{r initial_setup, echo=FALSE, message=FALSE, warning=FALSE}
library(REDCapR)
library(knitr)
library(plyr)
library(dplyr)
library(magrittr)
library(GAMUT)
library(zoo)
library(beeswarm)
library(qicharts)
library(rworldmap)


options(scipen = 10)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      comment = "", dev = 'pdf',
                      fig.height = 2.5)

source('beeswarm_plot.R')
source('beeswarm_plot_1k.R')
source('beeswarm_plot_10k.R')
source('shadowtext.R')
source('show_plotData.R')
source('metric_results.R')
source('show_runchart.R')
source('measure_summary.R')
source('show_timeData.R')
source('map_gamut.R')
source('dag_results.R')
source('dd.R')
source('dag_CI.R')

```
```{r load_data, eval = TRUE}
# Uncomment next line to get new data from REDCap
#GAMUT_data("GAMUT.Rdata")
load("GAMUT.Rdata")

## time data
#time_data <- 
#        monthly_data %>%
#        select(program_name, month, total_patients, mean_mobilization, stemi_cases,
#               mean_bedside_stemi, mean_scene_stemi) %>%
#    filter(month < params$end_date)

# Filter past 12 months 
monthly_data <- filter(monthly_data,
                       month >= params$start_date & 
                       month < params$end_date)

dag <- params$dag
org <- params$org
program_name <- params$program_name

```



## Ventilator utilization - Adult  

```{r adult_vent_adv_airway, fig.height = 4, fig.path="figures/", include=TRUE, eval=TRUE, message=FALSE, echo=FALSE, warning=FALSE, error=FALSE}

dag_results(measure = "AA-1c", dag = dag, org = org)

```
