---
title: "overview"
author: "Rollie Parrish"
date: "March 12, 2016"
output: html_document

---

```{r setup, include=FALSE}
library(dplyr)
library(GAMUT)

knitr::opts_chunk$set(echo = FALSE)
```

```{r overview data, eval = TRUE}

#load("GAMUT.Rdata")

# Filter 
 # monthly_data <- filter(monthly_data,
 #                        month >= params$start_date & 
 #                        month < params$end_date)

overview <- list()

overview$enrolled <- 
        redcap_data %>%
        with(., levels(as.factor(program_name))) %>%
        length()

overview$partial <- 
        monthly_data %>%
        group_by(program_name, month) %>%
        group_by(program_name) %>%
        dplyr::summarise(n = n()) %>%
        filter(n < 12) %>%
        nrow()

overview$full <- 
        monthly_data %>%
        group_by(program_name, month) %>%
        group_by(program_name) %>%
        dplyr::summarise(n = n()) %>%
        filter(n == 12) %>%
        nrow()

overview$total_contacts <- 
        monthly_data %>%
        with(., sum(total_patients))

overview$countries <- 6


```

# Overview

- `r overview$enrolled` Total programs enrolled 
- `r overview$partial` New programs (partial data during past 12 months)
- `r overview$full` Established programs (data for all 12 months)
- `r overview$total_contacts` Total patient contacts (12 months)
- Rolling 12 months from `r start_date` to `r end_date`
- Data refreshed:  `r GAMUT_date_loaded`


```{r participant months, fig.width = 4, fig.align="center"}

participant_months <- 
        monthly_data %>%
        group_by(program_name, month) %>%
        group_by(program_name) %>%
        dplyr::summarise(n = n()) 

par(mar=c(5,6,4,2))
hist(participant_months$n, 
     main = "", 
     #xlab = "Number of months with data",
     ylab = "count",
     xlab = "Distribution of programs \nby number of months with data",
     cex.main  = .8, 
     cex.axis  = .8,
     cex.lab   = .8,
     las = 1)

```


```{r map gamut, fig.width = 10, fig.height = 6, fig.align = "center", eval = FALSE}
#- `r overview$countries` Countries represented
map_gamut()

```

