---
title: "introduction"
author: "Rollie Parrish"
date: "March 12, 2016"
output: pdf_document
---


## Introduction   

Dear Colleagues,  

It is an exciting time for the field of critical care transport and for the GAMUT (Ground and Air Medical qUality in Transport) Database.  Most of you are aware that the GAMUT Database was born out of the commitment by the American Academy of Peditatrics - Section on Transport Medicine (AAP-SOTM) and the Air Medical Physician Association (AMPA) to continually improve the quality of transport care for infants, children, and adults.  

Some of you may also know that the GAMUT Database has just celebrated its 1st birthday.  During that year, the GAMUT Database has seen over 100 transport programs register and over 100,000 patient contacts cataloged.  Not dissimilar from a baby learning to crawl and eventually walk around its 1st birthday, the GAMUT database is developing and maturing after turning one.  

We've developed a GAMUT database oversight committee - consisting of AMPA, AAP-SOTM, and other stakeholders.  That group will help guide the project as it grows -- and more importantly as strides are made around quality improvement projects.  We've begun to embark on a number of projects leveraging the data to drive improvement: one project focusing on neonatal and pediatric waveform capnography and another focusing on pediatric pain assessment.  We are exploring opportunities for leveraging improvement work for Maintenance of Certification requirements amongst some subspecialty boards.  We are initiating the steps in gaining National Quality Foundation endorsement for the quality metrics.  

Most importantly, we've identified two priorities for 2015-16.  First, the GAMUT database oversight committee wants to focus on the product delivered to you -- the database participants.  We want to ensure accurate, timely, and useful data returned to transport programs to permit programs to benchmark against their industry peers.  We're exploring dashboard and run chart software options -- though those won`t be immediately ready.  Second, the oversight committee is focusing on funding opportunities to ensure sustainability and infrastructure to support the quality improvement work that will develop once we gain awareness of our performance around these consensus quality metrics.  

In reviewing your program's performance on the attached data, please consider how your program`s performance compares to other programs.  Please gather your questions, use the Data Managers Google Group for additional thoughts, and mark your calendars for a GAMUT users webinar on April 20 at 10:30 AM Eastern (7:30 AM Pacific).  Details will be distributed via the Google Group.  

On behalf of the GAMUT database oversight committee,  



   Michael T. Bigham, MD, FAAP, FCCM  
   
   Pediatric Intensivist, Division of Critical Care Medicine  
   Medical Director, Transport Services  
   Assistant Patient Safety Officer  
   Clinical Assistant Professor, NEOMED  
   mbigham@chmca.org  
   


 Hamilton P. Schwartz, MD, MEd, FAAP, FACEP
 
 EMS Medical Director, Cincinnati Children's  
 Medical Director, Cincinnati Children's Transport Team  
 Associate Professor, UC Department of Pediatrics  
 hamilton.schwartz@cchmc.org  

